### NumPy program to test whether none of the elements of a given array is zero.
### NumPy program to test whether any of the elements of a given array is non-zero.

In [4]:
import numpy as np

def test_array_zeros(arr):
    if np.all (arr != 0):
        return print("None of the element in the array is zero")
    else:
        return print("At least one element in the array is zero")
    
# Test the function
arr = np.array([1, 2, 3, 4, 5])

test_array_zeros(arr)

arr = np.array([0, 2, 3, 4, 5])

test_array_zeros(arr)


None of the element in the array is zero
At least one element in the array is zero


### NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given

In [5]:
def compare_arrays (arr1,arr2,tolerance):
    arr1=np.array(arr1)
    arr2=np.array(arr2)
    
    equality=np.equal(arr1,arr2)
    with_tolerance=np.isclose(arr1,arr2,atol=tolerance)
    
    return equality, with_tolerance
array1=[0,1,2,3,4,5,6]
array2=[0,1,2.3,3,4,5.1,6.2]
tolerance=0.2
compare_arrays(array1,array2,tolerance)

(array([ True,  True, False,  True,  True, False, False]),
 array([ True,  True, False,  True,  True,  True,  True]))

### NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [6]:
zeros=np.zeros(10)
ones=np.ones(10)
fives=np.full(10,5)
print(f"Zeros array=\n{zeros}\nOnes array=\n{ones}\nFives array\n{fives}")

Zeros array=
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Ones array=
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Fives array
[5 5 5 5 5 5 5 5 5 5]


### NumPy program to create an array of the integers from 30 to70.

In [10]:
array30to70=np.arange(30,71)
print(array30to70)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


### NumPy program to create a 3x3 identity matrix

In [12]:
_3x3identyty=np.eye(3)
print(_3x3identyty)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### NumPy program to generate a random number between 0 and 1

In [16]:
random_num_0_1=np.random.rand()
print(random_num_0_1)

0.09553950179333104


### NumPy program to generate an array of 15 random numbers from a standard normal distribution

In [17]:
random_num=np.random.rand(15)
print(random_num)

[0.6251822  0.52091569 0.20134599 0.86752496 0.07541606 0.54588781
 0.6104359  0.88328169 0.8952219  0.53404803 0.86453727 0.18933984
 0.94485996 0.71742568 0.78965302]


### NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

In [19]:
vector= np.arange(16,55)
print(vector)

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


### NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10

In [20]:
vector= np.random.randint(0,11, size=5)
print(vector)

[ 9 10  5  5  0]


### NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [27]:
matrix= np.zeros((10,10))
matrix[0, :]=1
matrix[: ,0]=1
matrix[-1, :]=1
matrix[: , -1]=1
print(matrix)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [29]:
matrixd=np.zeros((5,5))
np.fill_diagonal(matrixd,[1,2,3,4,5])
print(matrixd)


[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


### NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.

In [36]:
matrix4=np.ones((4,4))
np.fill_diagonal(matrix4, 0)
matrix4[1::2, ::2] = 0
matrix4[::2, 1::2] = 0

print(matrix4)

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


### NumPy program to save two given arrays into a single file in compressed format (.npz format) and load it.

In [43]:
array11=np.array([1,2,3,4,5])
array22=np.array([6,7,8,9,10])
np.savez_compressed('array.npz',array111=array11,array222=array22)
loaded_data= np.load('array.npz')
loaded_array1 = loaded_data['array111']
loaded_array2=loaded_data['array222']
print(loaded_array1)
print(loaded_array2)

[1 2 3 4 5]
[ 6  7  8  9 10]


### NumPy program to create a one-dimensional array of forty pseudo-randomly generated values. Select

In [82]:
random_array=np.random.randn(40)
print (random_array)

[ 0.94246389 -1.05069037 -1.18458538  0.54995502 -0.94408177 -0.71612958
  0.91376905 -0.35472242 -1.14931398 -0.73759777 -1.01934039  0.51468735
 -0.80120629  0.87318777 -0.36764631 -0.36882394 -1.13627214  0.23915895
  1.49961487 -0.11115076 -0.33151431 -1.40318607  2.46929378  1.34756962
  0.88756786 -0.22204582 -0.41026287 -0.7031011   0.45507757  0.35687894
 -1.28751665  0.5708277  -0.01913947  0.93812616  0.85749702 -0.07787328
  0.60738702 -2.10479133 -1.12985998  0.42255251]
